version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package.json" }}

      - run: npm run install-ci

      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}

      - run: npm run build-prod-ci

      # need unique id to link this cache to deploy step, such that no rebuild is needed.
      # it's however not possible to use environment variables in cache-key names, so have to save it to file first
      - run: echo "$CIRCLE_WORKFLOW_ID" > _env_var_holder

      - save_cache:
          paths:
            - ~/repo/dist/
          key: frontend-artifact-{{ checksum "_env_var_holder" }}


  deploy:
    machine: true

    working_directory: ~/repo

    steps:
      - run: echo "$CIRCLE_WORKFLOW_ID" > _env_var_holder

      - restore_cache:
          keys:
            - frontend-artifact-{{ checksum "_env_var_holder" }}

      - add_ssh_keys:
          fingerprints:
            - "5b:01:54:2b:8b:cc:57:20:c0:be:2c:24:f6:22:18:81"

      # always return true, in case there is nothing to delete.
      - run: ssh -o stricthostkeychecking=no $SSH_USER@$SSH_HOST "rm -r /var/www/angular/* || true"

      - run: scp -rq -o stricthostkeychecking=no dist/website-frontend/* $SSH_USER@$SSH_HOST:/var/www/angular/

workflows:
  version: 2
  package-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
